# Generated by Django 4.1.5 on 2023-02-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justix', '0002_alter_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.CharField(max_length=255, verbose_name='Фейзбук'),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.CharField(max_length=255, verbose_name='Инстаграм'),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin',
            field=models.CharField(max_length=255, verbose_name='Линкедин'),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.CharField(max_length=255, verbose_name='Твиттер'),
        ),
    ]
