# Generated by Django 4.1.5 on 2023-02-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justix', '0004_alter_team_facebook_alter_team_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='link',
            field=models.CharField(max_length=255, unique=True, verbose_name='Ссылка'),
        ),
    ]
