# Generated by Django 4.1.5 on 2023-02-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justix', '0005_alter_category_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.CharField(max_length=255, unique=True, verbose_name='Текст')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['id']},
        ),
    ]
