# Generated by Django 4.1.5 on 2023-02-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justix', '0006_main_alter_category_options_alter_team_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='text',
            field=models.TextField(unique=True, verbose_name='Текст'),
        ),
    ]
