# Generated by Django 4.1.5 on 2023-02-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justix', '0007_alter_main_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='class_class',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='main',
            name='class_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID'),
        ),
    ]
