# Generated by Django 4.1.5 on 2023-02-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justix', '0009_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.CharField(max_length=255, verbose_name='Stack')),
                ('price', models.CharField(blank=True, max_length=255, verbose_name='Price')),
                ('skills', models.TextField(blank=True, verbose_name='Skills')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
