# Generated by Django 4.1.5 on 2023-04-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justix', '0010_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, verbose_name='подробно'),
        ),
    ]
